use super::ManualHostState;
use katana_chat_ui::{
    ChatOutputKind, ChatSessionError, DiffCandidateOutput, FileCandidateOutput,
    PermissionRequestOutput,
};

impl ManualHostState {
    pub(crate) fn add_sample_outputs(&mut self, assistant_id: u64) -> Result<(), ChatSessionError> {
        self.session.add_output(assistant_id, Self::sample_file())?;
        self.session.add_output(assistant_id, Self::sample_diff())?;
        self.session
            .add_output(assistant_id, Self::sample_permission())?;
        Ok(())
    }

    fn sample_file() -> ChatOutputKind {
        ChatOutputKind::FileCandidate(FileCandidateOutput::new(
            "tmp/kcu-generated.md",
            "text/markdown",
            "# generated by katana-chat-ui",
        ))
    }

    fn sample_diff() -> ChatOutputKind {
        ChatOutputKind::DiffCandidate(DiffCandidateOutput::new(
            "src/lib.rs",
            "--- a/src/lib.rs\n+++ b/src/lib.rs\n@@ -1 +1 @@\n-hello\n+hello kcu\n",
        ))
    }

    fn sample_permission() -> ChatOutputKind {
        ChatOutputKind::PermissionRequest(PermissionRequestOutput::new(
            "just check を実行",
            "host 側が明示操作として扱う確認用 request",
        ))
    }
}
