[package]
name = "e2e-host-app"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
floem = { git = "https://github.com/lapce/floem", rev = "f2ce49556606db6d8f025443f834f04b7a6b4796" }
katana-chat-ui = { path = "../../crates/katana-chat-ui" }
katana-chat-ui-floem = { path = "../../crates/katana-chat-ui-floem" }
serde_json = "1.0"
